module.exports = [
    `
    name
    salary
    stress
    pros
    cons
    facts
    activities
    advancement
    alternativeQualifications
    apprentice
    areasGrowth
    areasKnowledge
    assets
    attributesPersonal
    background
    careerLongevity
    careerPathVariability
    careerReputation
    challenges
    characteristics
    constraints
    credentials
    decisionMaking
    descriptions
    effects
    entryPoint
    familyLife
    frustrations
    importantIndustryPeople
    interests
    keySkills
    professionalJournals
    professionalOrganizations
    sacrifices
    satisfaction
    supervise
    takeWorkHome
    technology
    vacation
    `
]
